/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentresultmanagementsystem;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author nishu
 */
public class studentHome extends javax.swing.JFrame {

    /**
     * Creates new form studentHome
     */
    public studentHome() {
        initComponents();
        setResizable(false);
        setImage();
    }

    public studentHome(String rollno) {
        initComponents();
        etRollNo.setText(rollno);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        etCourseName = new javax.swing.JTextField();
        etRollNo = new javax.swing.JTextField();
        etName = new javax.swing.JTextField();
        etBranch = new javax.swing.JTextField();
        etGender = new javax.swing.JTextField();
        etFatherName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        dsaText = new javax.swing.JLabel();
        dbmsText = new javax.swing.JLabel();
        osText = new javax.swing.JLabel();
        cnText = new javax.swing.JLabel();
        sdText = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        totalMarks = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        statusText = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        percentageText = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Father Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 90, 83, -1));

        jLabel2.setText("Course Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 70, -1));

        jLabel4.setText("Roll Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, -1));

        jLabel5.setText("Branch");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 70, -1));

        jLabel6.setText("Gender");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 70, -1));

        etCourseName.setEditable(false);
        getContentPane().add(etCourseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 7, 150, -1));

        etRollNo.setEditable(false);
        getContentPane().add(etRollNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 87, 150, -1));

        etName.setEditable(false);
        getContentPane().add(etName, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 47, 150, -1));

        etBranch.setEditable(false);
        getContentPane().add(etBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 7, 150, -1));

        etGender.setEditable(false);
        getContentPane().add(etGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 47, 150, -1));

        etFatherName.setEditable(false);
        getContentPane().add(etFatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 87, 150, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("DSA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 65, 33, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("DBMS");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 114, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("OS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 168, 33, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("CN");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 222, 33, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("SD");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 266, 33, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel12.setText("Total Marks");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 28, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel13.setText("Passing Marks");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 28, 160, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel14.setText("Marks Obtained");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(436, 28, -1, -1));

        jLabel15.setText("100");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 65, 77, -1));

        jLabel16.setText("100");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 114, 77, -1));

        jLabel17.setText("100");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 222, 77, -1));

        jLabel18.setText("100");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 168, 77, -1));

        jLabel19.setText("100");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 266, 77, -1));

        jLabel20.setText("30");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 114, 142, -1));

        jLabel21.setText("30");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 65, 142, -1));

        jLabel22.setText("30");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 168, 142, -1));

        jLabel23.setText("30");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 222, 142, -1));

        jLabel24.setText("30");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 266, 142, -1));

        dsaText.setText("30");
        jPanel1.add(dsaText, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 103, -1));

        dbmsText.setText("30");
        jPanel1.add(dbmsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 114, 103, -1));

        osText.setText("30");
        jPanel1.add(osText, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 168, 103, -1));

        cnText.setText("30");
        jPanel1.add(cnText, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 222, 103, -1));

        sdText.setText("30");
        jPanel1.add(sdText, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 266, 103, -1));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel30.setText("Total Marks");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 317, -1, -1));

        totalMarks.setText("500");
        jPanel1.add(totalMarks, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 30, -1));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setText("Status");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        statusText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        statusText.setText("Pass");
        jPanel1.add(statusText, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, -1));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel34.setText("Percentage");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 204, -1, -1));

        percentageText.setText("95%");
        jPanel1.add(percentageText, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 204, 34, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentresultmanagementsystem/icons8-login-30.png"))); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 320, 91, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 700, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try {
            String rollno = etRollNo.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/srm", "root", "Nishu1234");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from student inner join result where student.rollno='" + rollno + "' and result.rollno='" + rollno + "'");
            if (rs.next()) {
                etCourseName.setText(rs.getString(2));
                etBranch.setText(rs.getString(3));
                etName.setText(rs.getString(4));
                etGender.setText(rs.getString(5));
                etFatherName.setText(rs.getString(6));
                dsaText.setText(rs.getString(8));
                dbmsText.setText(rs.getString(9));
                osText.setText(rs.getString(10));
                cnText.setText(rs.getString(11));
                sdText.setText(rs.getString(12));

                //Total
                int s1 = Integer.parseInt(dsaText.getText());
                int s2 = Integer.parseInt(dbmsText.getText());
                int s3 = Integer.parseInt(osText.getText());
                int s4 = Integer.parseInt(cnText.getText());
                int s5 = Integer.parseInt(sdText.getText());
                int totalSum = s1 + s2 + s3 + s4 + s5;
                int percent = (totalSum * 100) / 500;
                int avg = totalSum / 5;
                totalMarks.setText(String.valueOf(totalSum));
                percentageText.setText(String.valueOf(percent + "%"));

                if (avg > 30) {
                    statusText.setText("Pass");
                } else {
                    statusText.setText("Fail");
                }
////        String per=String.valueOf(percent);
//        if(percent<=75){
//            divisionText.setText("First");
//        }else if(percent>=75&&percent<=60){
//             divisionText.setText("Second");
//        }else if(percent>=60&&percent<=50){
//             divisionText.setText("Third");
//        }
//        divisionText.setText("Average");
            }
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }

    }//GEN-LAST:event_formComponentShown

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new studentAdmin().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel cnText;
    private javax.swing.JLabel dbmsText;
    private javax.swing.JLabel dsaText;
    private javax.swing.JTextField etBranch;
    private javax.swing.JTextField etCourseName;
    private javax.swing.JTextField etFatherName;
    private javax.swing.JTextField etGender;
    private javax.swing.JTextField etName;
    private javax.swing.JTextField etRollNo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel osText;
    private javax.swing.JLabel percentageText;
    private javax.swing.JLabel sdText;
    private javax.swing.JLabel statusText;
    private javax.swing.JLabel totalMarks;
    // End of variables declaration//GEN-END:variables
private void setImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("student.png")));
    }
}
