/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentresultmanagementsystem;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author nishu
 */
public class update extends javax.swing.JFrame {

    /**
     * Creates new form update
     */
    public update() {
        initComponents();
        setResizable(false);
        setImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        insertnewstudent = new javax.swing.JButton();
        addnewstudent = new javax.swing.JButton();
        allstudent = new javax.swing.JButton();
        registeredstudent = new javax.swing.JButton();
        allstudent1 = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        etRollNo2 = new javax.swing.JTextField();
        etdsa = new javax.swing.JTextField();
        etdbms = new javax.swing.JTextField();
        updateResult = new javax.swing.JButton();
        etos = new javax.swing.JTextField();
        etcn = new javax.swing.JTextField();
        etsd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        etRollNo1 = new javax.swing.JTextField();
        etName = new javax.swing.JTextField();
        etFatherName = new javax.swing.JTextField();
        course = new javax.swing.JComboBox<>();
        gender = new javax.swing.JComboBox<>();
        branch = new javax.swing.JComboBox<>();
        updateStudent = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        insertnewstudent.setText("Insert New Student");
        insertnewstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertnewstudentActionPerformed(evt);
            }
        });

        addnewstudent.setText("Add New Student");
        addnewstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewstudentActionPerformed(evt);
            }
        });

        allstudent.setText("All Student Result");
        allstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allstudentActionPerformed(evt);
            }
        });

        registeredstudent.setText("Registered Student");
        registeredstudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registeredstudentActionPerformed(evt);
            }
        });

        allstudent1.setBackground(new java.awt.Color(255, 0, 0));
        allstudent1.setForeground(new java.awt.Color(255, 255, 255));
        allstudent1.setText("UpdateDetails");
        allstudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allstudent1ActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(0, 102, 102));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentresultmanagementsystem/shutdown.png"))); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        delete.setText("Delete Details");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(insertnewstudent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
            .addComponent(registeredstudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(allstudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addnewstudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(allstudent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(addnewstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(insertnewstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(registeredstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(allstudent, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(allstudent1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etRollNo2.setText("Roll No");
        jPanel2.add(etRollNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 48, 100, -1));

        etdsa.setText("DSA");
        jPanel2.add(etdsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 97, 100, -1));

        etdbms.setText("DBMS");
        jPanel2.add(etdbms, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 151, 100, -1));

        updateResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentresultmanagementsystem/update.png"))); // NOI18N
        updateResult.setText("Update Result");
        updateResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateResultActionPerformed(evt);
            }
        });
        jPanel2.add(updateResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 209, 294, -1));

        etos.setText("OS");
        jPanel2.add(etos, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 48, 100, -1));

        etcn.setText("CN");
        jPanel2.add(etcn, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 97, 100, -1));

        etsd.setText("SD");
        jPanel2.add(etsd, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 151, 100, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Student Result");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 540, 270));

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etRollNo1.setText("Roll No");
        jPanel3.add(etRollNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 32, 100, -1));

        etName.setText("Name");
        jPanel3.add(etName, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 96, 100, -1));

        etFatherName.setText("FatherName");
        jPanel3.add(etFatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 137, 100, -1));

        course.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B.Tech", "M.Tech", "BCA", "MCA", "B.Sc" }));
        jPanel3.add(course, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 32, 100, -1));

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Others", " " }));
        jPanel3.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 137, 100, -1));

        branch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CSE", "IT", "ECE", "EEE", "ME", "CE", " " }));
        jPanel3.add(branch, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 96, 100, -1));

        updateStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentresultmanagementsystem/update.png"))); // NOI18N
        updateStudent.setText("Update Student");
        updateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentActionPerformed(evt);
            }
        });
        jPanel3.add(updateStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 177, 294, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Student Details");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 6, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 540, 230));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insertnewstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertnewstudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new insertnewstudent().setVisible(true);
    }//GEN-LAST:event_insertnewstudentActionPerformed

    private void addnewstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewstudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new index().setVisible(true);
    }//GEN-LAST:event_addnewstudentActionPerformed

    private void allstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allstudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new allstudentresult().setVisible(true);
    }//GEN-LAST:event_allstudentActionPerformed

    private void registeredstudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registeredstudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new registeredstudent().setVisible(true);
    }//GEN-LAST:event_registeredstudentActionPerformed

    private void allstudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allstudent1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new update().setVisible(true);
    }//GEN-LAST:event_allstudent1ActionPerformed

    private void updateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentActionPerformed
        // TODO add your handling code here:
        String rollno = etRollNo1.getText();
        String courses = (String) course.getSelectedItem();
        String branchs = (String) branch.getSelectedItem();
        String name = etName.getText();
        String genders = (String) gender.getSelectedItem();
        String fathername = etFatherName.getText();
        if (etRollNo1.getText().isEmpty() || etName.getText().isEmpty() || etFatherName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter All Entries!");
        } else {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/srm", "root", "Nishu1234");

                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from student where rollno='" + rollno + "'");
                if (rs.next()) {
                    st.executeUpdate("update student set course='" + courses + "',branch='" + branchs + "',name='" + name + "',gender='" + genders + "',fathername='" + fathername + "' where rollno='" + rollno + "'");
                    setVisible(false);
                    new update().setVisible(true);
                    JOptionPane.showMessageDialog(null, "Update Entry Sucessfully");
                } else {
                    JOptionPane.showMessageDialog(null, "Student Roll Number not Valid");
                }

            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
    }//GEN-LAST:event_updateStudentActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new adminIndex().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new delete().setVisible(true);
    }//GEN-LAST:event_deleteActionPerformed

    private void updateResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateResultActionPerformed
        // TODO add your handling code here:
        String rollno = etRollNo2.getText();
        String DSA = etdsa.getText();
        String DBMS = etdbms.getText();
        String OS = etos.getText();
        String CN = etcn.getText();
        String SD = etsd.getText();
        if (etRollNo2.getText().isEmpty() || etdsa.getText().isEmpty() || etdbms.getText().isEmpty() || etos.getText().isEmpty() || etcn.getText().isEmpty() || etsd.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter All Entries!");
        } else {

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/srm", "root", "Nishu1234");

                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("select * from student where rollno='" + rollno + "'");
                if (rs.next()) {
                    st.executeUpdate("update result set dsa='" + DSA + "',dbms='" + DBMS + "',os='" + OS + "',cn='" + CN + "',sd='" + SD + "' where rollno='" + rollno + "'");
                    setVisible(false);
                    new update().setVisible(true);
                    JOptionPane.showMessageDialog(null, "Updated Marks!");
                } else {
                    JOptionPane.showMessageDialog(null, "Roll Not Generated!");
                }

            } catch (HeadlessException | ClassNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(null, e.toString());
            }
        }
    }//GEN-LAST:event_updateResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnewstudent;
    private javax.swing.JButton allstudent;
    private javax.swing.JButton allstudent1;
    private javax.swing.JComboBox<String> branch;
    private javax.swing.JComboBox<String> course;
    private javax.swing.JButton delete;
    private javax.swing.JTextField etFatherName;
    private javax.swing.JTextField etName;
    private javax.swing.JTextField etRollNo1;
    private javax.swing.JTextField etRollNo2;
    private javax.swing.JTextField etcn;
    private javax.swing.JTextField etdbms;
    private javax.swing.JTextField etdsa;
    private javax.swing.JTextField etos;
    private javax.swing.JTextField etsd;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JButton insertnewstudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton logout;
    private javax.swing.JButton registeredstudent;
    private javax.swing.JButton updateResult;
    private javax.swing.JButton updateStudent;
    // End of variables declaration//GEN-END:variables

    private void setImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("student.png")));
    }
}
